vich_uploader:
    db_driver: orm

    mappings:
        maisons:
            uri_prefix: /images/maisons
            upload_destination: '%kernel.project_dir%/public/images/maisons'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
